@CoinPurseApi_HostAddress = https://localhost:7000


POST {{CoinPurseApi_HostAddress}}/api/institution
Content-Type: application/json

{
  "Name": "Chase"
}

###

GET {{CoinPurseApi_HostAddress}}/api/institution

###

POST {{CoinPurseApi_HostAddress}}/api/account
Content-Type: application/json

{
  "Name": "Savings",
  "TaxTypeId": 1,
  "InstitutionId": 1
}

###

POST {{CoinPurseApi_HostAddress}}/api/balance
Content-Type: application/json

{
  "AccountId": 1,
  "PeriodId": 2,
  "Amount": 2000
}

###

@id=1
GET {{CoinPurseApi_HostAddress}}/api/account/{{id}}

###

@accountId=1
GET {{CoinPurseApi_HostAddress}}/api/balance/{{accountId}}

###