@CoinPurseApi_HostAddress = https://localhost:7000


POST {{CoinPurseApi_HostAddress}}/api/institution
Content-Type: application/json

{
  "Name": "Capital One"
}

###

GET {{CoinPurseApi_HostAddress}}/api/institution

###

GET {{CoinPurseApi_HostAddress}}/api/account

###

POST {{CoinPurseApi_HostAddress}}/api/account
Content-Type: application/json

{
  "Name": "I Bonds",
  "TaxTypeId": 1,
  "InstitutionId":5
}

###

POST {{CoinPurseApi_HostAddress}}/api/balance
Content-Type: application/json

{
  "AccountId": 1,
  "Amount": 1000
}

###

@id=2
GET {{CoinPurseApi_HostAddress}}/api/account/{{id}}

###